version: '3.9'

services:
  app:
    image: music
    build: 
      context: .
      args:
        - DB_HOST=$DB_HOST
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    env_file:
      - .env    
    ports:
      - 80:8080

  db:
    image: mysql
    env_file:
      - .db.env
    ports:
      - "3309:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 5s